<a href="https://colab.research.google.com/github/machiobrian/Hugging_Face/blob/master/turkish_wav2vec2/evaluate_w2v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
%%capture
! pip install datasets
! pip install torchaudio
! pip install huggingface_hub
! pip install transformers
! pip install librosa
! pip install jiwer

In [2]:
# since we are looking forward to downloading the model, we use the read API access key
from huggingface_hub import notebook_login
notebook_login()

Token is valid.
Your token has been saved in your configured git credential helpers (store).
Your token has been saved to /root/.huggingface/token
Login successful


In [37]:
# load the model
from transformers import Wav2Vec2Tokenizer, Wav2Vec2ForCTC, Wav2Vec2Processor, AutoModelForCTC

In [8]:
! unzip /content/drive/MyDrive/turkish.zip

Archive:  /content/drive/MyDrive/turkish.zip
  inflating: turkish.wav             


In [36]:
import IPython.display as display
file = display.Audio("/content/turkish.wav", autoplay=False)
file

/content/drive/MyDrive/Datasets/timit/data/TEST/DR1/FAKS0/SA1.WAV

In [25]:
#set the sampling rate
import librosa
audio, rate = librosa.load('/content/turkish.wav', sr=16000)

In [27]:
audio, rate

(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 16000)

In [38]:
model = AutoModelForCTC.from_pretrained("cahya/wav2vec2-base-turkish-artificial")
processor = Wav2Vec2Processor.from_pretrained("cahya/wav2vec2-base-turkish-artificial")
tokenizer = Wav2Vec2Tokenizer.from_pretrained('cahya/wav2vec2-base-turkish-artificial')

/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py:369: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(


In [49]:
model = AutoModelForCTC.from_pretrained("ix502iv/wa2vec2-large-xls-r-colab_turkish")
processor = Wav2Vec2Processor.from_pretrained("ix502iv/wa2vec2-large-xls-r-colab_turkish")
tokenizer = Wav2Vec2Tokenizer.from_pretrained('ix502iv/wa2vec2-large-xls-r-colab_turkish')

Downloading:   0%|          | 0.00/2.06k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/214 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/291 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/429 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/96.0 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.8/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:752: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [50]:
input_values = tokenizer(audio, return_tensors='pt').input_values
input_values

tensor([[0., 0., 0.,  ..., 0., 0., 0.]])

In [51]:
# get and store logits
logits = model(input_values).logits
logits

tensor([[[-1.6526, -1.4384, -2.4773,  ..., -6.2739, -6.8264, 11.2380],
         [-0.0553,  1.1867, -1.4635,  ..., -0.6875, -0.7245,  0.1870],
         [-1.1765, -1.1716, -3.8441,  ..., -6.5666, -7.1338, 11.8231],
         ...,
         [-1.1736, -1.5885, -3.4205,  ..., -6.7694, -7.3118, 12.2882],
         [-1.4636, -1.4296, -3.4347,  ..., -6.7599, -7.2887, 12.2375],
         [ 1.1851, -1.7970, -1.6041,  ..., -1.4015, -1.5457,  2.1767]]],
       grad_fn=<ViewBackward0>)

In [52]:
import torch
prediction = torch.argmax(logits, dim=-1)
prediction

tensor([[37,  5, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
         37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 18, 37, 37, 37, 11, 37, 37,  5,
         37, 37, 14,  0,  0, 37, 16, 37, 37,  1,  1, 37, 18, 18, 12, 12,  1,  1,
         37, 13, 13, 37,  5, 37, 14, 37, 37, 37, 20, 37, 15, 37,  0,  0, 37, 19,
         37,  5, 37, 37, 37, 37, 27, 37,  9, 37, 13, 37, 37, 37, 12,  5,  5, 37,
         18,  9,  9, 14, 37,  5,  0,  0, 37,  7,  9, 37, 37, 37,  4, 37,  9,  9,
         37, 12, 37, 37, 37, 13,  5, 37, 37, 37, 37, 19, 37,  9, 14, 37,  9,  0,
          0,  2, 37,  5, 37, 37, 37, 37, 11, 11, 37, 12, 12,  9, 37, 25, 15, 15,
         15, 37, 18,  0,  0, 13, 13, 21, 21, 37, 37, 37, 19, 21, 21, 37, 14, 37,
         21, 21, 21, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
         37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
         37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
         37, 37, 37, 37, 37,

In [53]:
# erken parlamento seçimlerine gidilmesini bekliyor musunuz

transcription = tokenizer.batch_decode(prediction)[0]
transcription

'erken parlamento seçimlerine gidilmesini bekliyor musunuz'

**Noted a difference in performance and accuracy:**
* This is the text to output:

`erken parlamento seçimlerine gidilmesini bekliyor musunuz`
* Efe's model (cahya/wav2vec2-base-turkish-artificial)

`ahkem parno anti seçimlerne gelmesini bekliyor musunuz`

* Machio's model
(ix502iv/wa2vec2-large-xls-r-colab_turkish)

`erken parlamento seçimlerine gidilmesini bekliyor musunuz`